jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  scmCheckoutRetryCount: 2
  labelAtoms:
  - name: "built-in"
  - name: "jenkins-jenkins-agent"
  - name: "master"
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pipelineStepsAWS:
    enableCredentialsFromNode: false
  pollSCM:
    pollingThreadCount: 10
  thinBackup:
    backupAdditionalFiles: false
    backupBuildArchive: false
    backupBuildResults: false
    backupBuildsToKeepOnly: false
    backupConfigHistory: false
    backupNextBuildNumber: false
    backupPath: "/var/jenkins_home/thinBackup/"
    backupPluginArchives: false
    backupUserContents: false
    cleanupDiff: true
    failFast: true
    forceQuietModeTimeout: 120
    moveOldBackupsToZipFile: false
    nrMaxStoredFull: 7
    waitForIdle: false
tool:
  go:
    installations:
    - name: "Go-1.21.9"
      properties:
      - installSource:
          installers:
          - golangInstaller:
              id: "1.21.9"
jobs:
  - file: inadev-job.groovy