apiVersion: apps/v1
kind: Deployment
metadata:
  name: wapi-deploy
  namespace: wapi
  labels:
    app: wapi-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wapi
  template:
    metadata:
      labels:
          app: wapi
          role: api
    spec:
      containers:
      - name: wapi
        image: jose9123/wapi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080