apiVersion: apps/v1
kind: Deployment
metadata:
  name: wapi-deploy
  namespace: wapi
  labels:
    app: wapi-deploy
spec:
replicas: 1
  selector:
    matchLabels:
      app: wapi
  template:
    metadata:
   aws configure set region "us-east-1".   labels:
        app: wapi
        role: api
    spec:
      containers:
      - name: wapi
        image: jose9123/wapi:latest
        ports:
        - containerPort: 8080