apiVersion: v1
kind: Service
metadata:
  name: wapi
  namespace: wapi
  labels:
    app: wapi-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: wapi
    role: api
  type: LoadBalancer

