apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: wapi
  name: wapi-admins
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wapi-rolebinding
  namespace: wapi
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: jenkins
  apiGroup: ""
roleRef:
  kind: Role
  name: wapi-admins
  apiGroup: ""